<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Receipt {{ $payment->receipt_number }}</title>
    @include('pdf.partials.document-styles')
</head>
<body>
    <div class="pdf-shell">
        <div class="pdf-header">
            <table class="pdf-header-table">
                <tr>
                    <td>
                        <h1 class="pdf-title" style="color: {{ $school->primary_color }}">{{ $school->name }}</h1>
                        <div class="pdf-muted">{{ $school->address }}</div>
                        <div class="pdf-muted">{{ $school->phone }} {{ $school->email }}</div>
                    </td>
                    <td class="pdf-right">
                        <div class="pdf-muted">Receipt</div>
                        <div class="pdf-subtitle">{{ $payment->receipt_number }}</div>
                    </td>
                </tr>
            </table>
        </div>

        <table class="pdf-kv">
            <tr>
                <td><span class="pdf-label">Student</span><span class="pdf-value">{{ $payment->student?->name }}</span></td>
                <td><span class="pdf-label">Paid on</span><span class="pdf-value">{{ $payment->paid_on->format('d M Y') }}</span></td>
            </tr>
            <tr>
                <td><span class="pdf-label">Fee</span><span class="pdf-value">{{ $payment->studentFee?->feeHead?->name }}</span></td>
                <td><span class="pdf-label">Method</span><span class="pdf-value">{{ ucfirst(str_replace('_', ' ', $payment->method)) }}</span></td>
            </tr>
        </table>

        <div class="pdf-panel">
            <div class="pdf-label">Amount received</div>
            <div class="pdf-panel-total">PKR {{ number_format($payment->amount, 2) }}</div>
        </div>

        <table class="pdf-signatures">
            <tr>
                <td><div class="pdf-signature-line">Generated by system</div></td>
                <td><div class="pdf-signature-line pdf-signature-line-right">Authorized signature</div></td>
            </tr>
        </table>
    </div>

    @if (empty($pdf))
        <div class="pdf-actions">
            <a href="{{ request()->fullUrlWithQuery(['download' => 1]) }}">Download PDF</a>
            <button onclick="window.print()">Print / Save PDF</button>
        </div>
    @endif
</body>
</html>
